
package com.chehejia.ota.model;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OtaIntegrationServiceService", targetNamespace = "http://controllers.integration.jiangda.com/", wsdlLocation = "/otaInteService.wsdl")
public class OtaIntegrationServiceService
    extends Service
{

    private final static URL OTAINTEGRATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException OTAINTEGRATIONSERVICESERVICE_EXCEPTION;
    private final static QName OTAINTEGRATIONSERVICESERVICE_QNAME = new QName("http://controllers.integration.jiangda.com/", "OtaIntegrationServiceService");

    static {
        OTAINTEGRATIONSERVICESERVICE_WSDL_LOCATION = OtaIntegrationServiceService.class.getResource("/otaInteService.wsdl");
        WebServiceException e = null;
        if (OTAINTEGRATIONSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/otaInteService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        OTAINTEGRATIONSERVICESERVICE_EXCEPTION = e;
    }

    public OtaIntegrationServiceService() {
        super(__getWsdlLocation(), OTAINTEGRATIONSERVICESERVICE_QNAME);
    }

    public OtaIntegrationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OTAINTEGRATIONSERVICESERVICE_QNAME, features);
    }

    public OtaIntegrationServiceService(URL wsdlLocation) {
        super(wsdlLocation, OTAINTEGRATIONSERVICESERVICE_QNAME);
    }

    public OtaIntegrationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OTAINTEGRATIONSERVICESERVICE_QNAME, features);
    }

    public OtaIntegrationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OtaIntegrationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OtaIntegrationService
     */
    @WebEndpoint(name = "OtaIntegrationServicePort")
    public OtaIntegrationService getOtaIntegrationServicePort() {
        return super.getPort(new QName("http://controllers.integration.jiangda.com/", "OtaIntegrationServicePort"), OtaIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OtaIntegrationService
     */
    @WebEndpoint(name = "OtaIntegrationServicePort")
    public OtaIntegrationService getOtaIntegrationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllers.integration.jiangda.com/", "OtaIntegrationServicePort"), OtaIntegrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OTAINTEGRATIONSERVICESERVICE_EXCEPTION!= null) {
            throw OTAINTEGRATIONSERVICESERVICE_EXCEPTION;
        }
        return OTAINTEGRATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
